name: Bug report
description: Report a bug with Haku. Please provide as much details as possible, including screenshots if necessary.
body:
  - type: markdown
    attributes:
      value: Thanks for filing an issue 😄 !
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '…'
        2. Click on '…'
        3. Scroll down to '…'
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
  - type: dropdown
    attributes:
      label: How often does this bug happen?
      description: How easily can you reproduce this bug?
      options:
        - Every time
        - Often
        - Sometimes
        - Only once
    validations:
      required: true
  - type: input
    attributes:
      label: Haku version
      placeholder: '1.12'
  - type: dropdown
    attributes:
      label: Haku environment
      description: Are you using the application in a browser or installed as a Progressive Web App?
      options:
        - Browser
        - PWA
    validations:
      required: true
  - type: input
    attributes:
      label: Browser version
      placeholder: Edge 102, Safari 15.4
  - type: input
    attributes:
      label: Operating System version
      placeholder: macOS Monterey 12.3
